default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: info-hound_development

test:
  <<: *default
  database: info-hound_test

production:
  <<: *default
  database: info-hound_production
  username: info-hound
  password: <%= ENV['INFO-HOUND_DATABASE_PASSWORD'] %>
